# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frittteui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://frittteregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e74a7faf726549c5a9f0293a9e2fb891 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_efdb94f2409d4ca8959ca55d342ad046 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: frittteregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e74a7faf726549c5a9f0293a9e2fb891 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frittteui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de521d43e9984e39a63ba14258e03723 }}
        images: 'frittteregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e74a7faf726549c5a9f0293a9e2fb891 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'